/* Read-only conversation UX. Conversation bodies are synthetic and never sent. */
'use strict';
window.AdminChat={render(){
 const A=window.Admin,{node,button}=A,root=node('div','page');root.append(A.pageHead());
 const form=node('form','card filter-panel'),sales=A.pageData('salesManage')?.tables?.[0],accounts=A.pageData('wechatStatus')?.tables?.[0],customers=(A.pageData('yxCustomerList')||A.pageData('customerManagement'))?.tables?.[0];
 const values=(t,label)=>[...new Set((t?.rows||[]).map(r=>r.cells[t.headers.indexOf(label)]).filter(Boolean))];
 const salesNames=values(sales,'销售姓名'),accountNames=values(accounts,'人设名称');
 function multi(label,options){const wrap=node('details','multi-filter'),summary=node('summary','',label+' · 全部');wrap.append(summary);const box=node('div','multi-options');options.forEach(v=>{const l=node('label','check-field'),c=node('input');c.type='checkbox';c.value=v;l.append(c,document.createTextNode(v));box.append(l);});box.onchange=()=>{const n=box.querySelectorAll('input:checked').length;summary.textContent=label+(n?' · 已选 '+n+' 项':' · 全部');};wrap.append(box);form.append(wrap);return box;}
 const salesPicker=multi('销售',salesNames),accountPicker=multi('人设',accountNames),keyword=node('input');keyword.placeholder='搜索客户昵称';keyword.setAttribute('aria-label','客户昵称');const keywordLabel=node('label','field');keywordLabel.append(node('span','','客户昵称'),keyword);form.append(keywordLabel);
 const period=node('select');['不限时间','今天','本月','自定义日期'].forEach(v=>period.append(new Option(v,v)));const timeLabel=node('label','field');timeLabel.append(node('span','','聊天时间'),period);form.append(timeLabel);
 const dates=node('div','date-range');dates.hidden=true;const from=node('input'),to=node('input');from.type=to.type='date';from.setAttribute('aria-label','聊天开始日期');to.setAttribute('aria-label','聊天结束日期');dates.append(from,document.createTextNode('至'),to);form.append(dates);period.onchange=()=>dates.hidden=period.value!=='自定义日期';
 const rows=(customers?.rows||[]).slice(0,30);const h=customers?.headers||[];const contacts=rows.map((r,i)=>({id:r.id,name:r.cells[h.indexOf('微信昵称')]||r.cells[h.indexOf('好友名称')]||'演示客户 '+(i+1),sales:r.cells[h.indexOf('专属销售')]||salesNames[i%Math.max(1,salesNames.length)]||'演示销售',account:r.cells[h.indexOf('所在账号')]||accountNames[i%Math.max(1,accountNames.length)]||'演示工作账号',date:'2026-09-'+String(18-i%7).padStart(2,'0')}));
 const list=node('aside','chat-list'),pane=node('div','chat-pane'),title=node('div','chat-title'),messages=node('div','messages'),footer=node('div','compose');footer.append(node('p','hint','只读演示 · 客户昵称来自本租户样本，对话正文为合成内容。'));pane.append(title,messages,footer);const panel=node('section','card'),split=node('div','chat-layout');split.append(list,pane);panel.append(split);
 let selected;function open(c){selected=c.id;title.replaceChildren(node('strong','',c.name),node('small','hint',c.sales+' · '+c.account));messages.replaceChildren(node('div','chat-date',c.date+' · 合成演示对话'));[{text:'您好，我想了解服务和预约安排。',time:'09:30',mine:false},{text:'您好，请告诉我您方便的时间，我可以为您介绍预约流程。',time:'09:32',mine:true},{text:'我先确认一下时间，稍后联系您。',time:'09:35',mine:false}].forEach(m=>{const e=node('div','message'+(m.mine?' mine':''));e.append(node('div','bubble',m.text),node('small','hint',m.time));messages.append(e);});list.querySelectorAll('.contact').forEach(e=>e.classList.toggle('active',e.dataset.id===selected));}
 function draw(initial=false){if(period.value==='自定义日期'&&from.value&&to.value&&from.value>to.value){A.toast('开始日期不能晚于结束日期');return;}const read=el=>[...el.querySelectorAll('input:checked')].map(i=>i.value),s=read(salesPicker),a=read(accountPicker);const matched=contacts.filter(c=>(!s.length||s.includes(c.sales))&&(!a.length||a.includes(c.account))&&c.name.includes(keyword.value.trim())&&(period.value!=='今天'||c.date==='2026-09-18')&&(period.value!=='本月'||c.date.startsWith('2026-09'))&&(period.value!=='自定义日期'||(!from.value||c.date>=from.value)&&(!to.value||c.date<=to.value)));
 list.replaceChildren(node('div','chat-list-heading','客户会话 · '+(initial?'待查询':matched.length+' 条')));title.textContent='聊天详情';messages.replaceChildren(A.empty(initial?'选择筛选条件后，点击查询':'选择客户会话后查看具体对话','仅展示本地样本；按最近匹配时间排序。'));if(initial)return;
 matched.forEach(c=>{const item=button('',()=>open(c),'contact');item.dataset.id=c.id;item.append(node('span','avatar',c.name[0]));const text=node('span','',c.name);text.append(node('small','',c.sales+' · '+c.date));item.append(text);list.append(item);});if(!matched.length)list.append(A.empty('没有匹配会话','调整销售、人设或时间条件。'));else open(matched.find(c=>c.id===selected)||matched[0]);}
 form.append(button('重置',()=>{form.reset();dates.hidden=true;form.querySelectorAll('.multi-filter summary').forEach((s,i)=>s.textContent=(i?'人设':'销售')+' · 全部');draw(false);}),button('查询',()=>draw(),'primary'));form.onsubmit=e=>{e.preventDefault();draw();};root.append(form,panel);A.$('app').replaceChildren(root);draw(false);
}};
